#!/bin/sh
set -e
CHROOT_DIR=/data/ubuntu
ENIGMA2_DIR=/usr/lib/enigma2/python/Plugins/Ubuntu/streamingserver
UBUNTU_DIR=$CHROOT_DIR/root/plugins/streamingserver
mkdir -p $UBUNTU_DIR
cp -avr $ENIGMA2_DIR/* $UBUNTU_DIR/

$CHROOT_DIR/root/mount_chroot
chroot "$CHROOT_DIR" /bin/bash -c "
    # Disable systemd
    echo -e '#!/bin/sh\nexit 0' > /var/lib/dpkg/info/systemd.postinst
    chmod +x /var/lib/dpkg/info/systemd.postinst
    dpkg --configure -a

    echo '[*] Updating plugin packages...'
    apt install -y ffmpeg
    /root/venv/bin/pip install -r /root/plugins/streamingserver/requirements.txt
"
$CHROOT_DIR/root/umount_chroot
echo "***********************************"
echo "*         streamingserver         *"
echo "*               by                *"
echo "*          dream-alpha            *"
echo "***********************************"
echo ""
echo "Plugin successfully installed."
exit 0
