#!/bin/sh
set -e
CHROOT_DIR=/data/ubuntu
chroot "$CHROOT_DIR" /bin/bash -c "
  echo '[*] Updating plugin packages...'
  /root/venv/bin/pip install -r /root/plugins/streamingserver/requirements.txt
"
echo "Plugin successfully installed."
echo "Please restart DreamOS now!"
exit 0
